spring.application.name=parking-lot

# Database Connections
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA Configs 
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.open-in-view=false
spring.http.encoding.charset=UTF-8

# Redis 3-Node Cluster Config for Redlock
redis.password=${REDIS_PASSWORD:}
redis.node1.host=${REDIS_NODE1_HOST:redis-1}
redis.node2.host=${REDIS_NODE2_HOST:redis-2}
redis.node3.host=${REDIS_NODE3_HOST:redis-3}

# Disable auto redis health contributor conflict
management.health.redis.enabled=false
spring.autoconfigure.exclude=org.redisson.spring.starter.RedissonAutoConfigurationV2
logging.level.org.springframework.security=DEBUG

# Enable Histogram Buckets for p95, p99 Latency Metrics
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=5ms,10ms,25ms,50ms,100ms,250ms,500ms,1s
